### ISSUE TITLE
大富翁的设计理念很好，但我安装ubuntu里的系统，其他都正常，但主程序启动不起来

### ISSUE THREAD

**Issue by fsz168** [zillionare/cfg4py#2]
主程序 zillionare 不能自启动，手动可以启动，但8888端口的jupyterlab又进入不了，我怀疑是这段命令的格式：

sudo -E bash zillionare.sh --target /usr/local/zillionare -- --jq_account 111111111 --jq_password 1111111111

这里的帐号密码，要不要加    <  >   的？  感谢hub主， 已star

**Comment by zillionare** [comment]
感谢使用！这个问题应该记录在[zillionare](https://github.com/zillionare/zillionare/issues)下。为了便于跟踪，可以麻烦你在那个repo下重开这个问题吗？我本来打算自己去开，但这样一来，你会看不到我的更新。

这个issue关掉了，因为问题与cfg4py无关。
